name: Docker Integration Tests

on: [push, pull_request]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
      - uses: actions/checkout@v2
      - name: run tests
      - run: ./tests/test.sh

